var now = new Date();
	var yr = now.getYear();
	var mName = now.getMonth() + 1;
	var dName = now.getDay() + 1;
	var dayNr = ((now.getDate()<10) ? "" : "")+ now.getDate();
	
	if(dName==1) Day = "Sunday";
	if(dName==2) Day = "Monday";
	if(dName==3) Day = "Tuesday";
	if(dName==4) Day = "Wednesday";
	if(dName==5) Day = "Thursday";
	if(dName==6) Day = "Friday";
	if(dName==7) Day = "Saturday";
	if(mName==1) Month="1";
	if(mName==2) Month="2";
	if(mName==3) Month="3";
	if(mName==4) Month="4";
	if(mName==5) Month="5";
	if(mName==6) Month="6";
	if(mName==7) Month="7";
	if(mName==8) Month="8";
	if(mName==9) Month="9";
	if(mName==10) Month="10";
	if(mName==11) Month="11";
	if(mName==12) Month="12";
	
	
	var todaysDate =(" "
	+ Day
	+ " - "
	+ Month
	+ "."
	+ dayNr
	+ "."
	);
		
	document.open();
	document.write(""+todaysDate+"</b> - <b>");
	
	today = new Date();
	den=today.getDate();
	mesic=(today.getMonth() + 1);
	if (mesic==1) {
	if (den==01) document.write("Amos, Genesis");
if (den==02) document.write("Cleo, Lavenia, Lavinia");
if (den==03) document.write("Dan, Dana, Danae, Dania, Daniela, Daniella, Danielle, Danika, Dannika, Danny, Dayana");
if (den==04) document.write("Franklin, Jasmin, Jasmine, Jazmin, Jazmine, Yasmeen, Yasmin, Yasmine");
if (den==05) document.write("Alvin, Carissa, Fay, Faye, Olympia");
if (den==06) document.write("Cooper, Cora, Coreen, Corene, Corey, Cori, Corie, Corina, Corine, Corinne, Corrie, Corrine, Cory, Corinne, Corrina, Korey, Kory");
if (den==07) document.write("Bronwyn, Imani, Josiah, Millard");
if (den==08) document.write("Aimee, Amy, Elvis, Jed, Piper");
if (den==09) document.write("Hunter, Kent, Kenton, Maude, Nona");
if (den==10) document.write("Jonah, Jonas, Dedra");
if (den==11) document.write("Allegra, Jalen, Porsha, Portia");
if (den==12) document.write("Jack, Jacki, Jackie, Jaclyn, Jacquelin, Jacqueline, Jacquelyn, Jake");
if (den==13) document.write("Forest, Kelsey, Kelsie, Tania, Tanya, Tana, Tanna");
if (den==14) document.write("Devan, Deven, Devin, Devon, Lorna, Lorne");
if (den==15) document.write("Consuelo, Martin, Martina, Marty");
if (den==16) document.write("Ayana, Ayanna, Leif");
if (den==17) document.write("Ben, Benedict, Benita, Benito, Benjamin, Bennie, Benny, Mohammed, Muhammad, Tamika");
if (den==18) document.write("Celeste, Celestina, Celestine, Doug, Douglas");
if (den==19) document.write("Cyrus, Erlinda, Kyra");
if (den==20) document.write("Fabian, Joy, Joyce");
if (den==21) document.write("Agnes, Annice, Anissa, Inez, Vicente, Vince, Vincent, Vincenzo, Vinnie");
if (den==22) document.write("Casey, Cassandra, Cassidy, Kasey, Kassandra, Kassidy, Zora, Zoraida");
if (den==23) document.write("Cesar, Keri, Kerri, Kerry");
if (den==24) document.write("Florence, Florent, Florinda, Flossie, Tim, Timmy, Timothy");
if (den==25) document.write("Berry, Beryl, Charity, Neal, Neil");
if (den==26) document.write("Jon, Jonathan, Jonathon, Tamara");
if (den==27) document.write("Esperanza, Nathan, Nathanael, Nathanie");
if (den==28) document.write("Alfonso, Alfred, Alfredo, Alonso, Alonzo, Avery");
if (den==29) document.write("Ashleigh, Ashlie, Ashley, Ashlyn, Ashlynn, Ashton, Ophrah, Oprah, Wilbert");
if (den==30) document.write("Daphne, Roosevelt");
if (den==31) document.write("Emely, Emil, Emilee, Emilia, Emilio, Emily, Milly, Porsha, Portia");
}
if (mesic==2) {
if (den==01) document.write("Harwey, Priscilla");
if (den==02) document.write("Eric, Vanesa, Vanessa");
if (den==03) document.write("Blase, Blaise, Kendall, Rosario");
if (den==04) document.write("Roni, Seth, Vera, Verena, Veronica");
if (den==05) document.write("Agatha, Ava, Avis, Braxton, Cole");
if (den==06) document.write("Alta, Ron, Ronald, Ronnie");
if (den==07) document.write("Ariel, Arielle, Arlen");
if (den==08) document.write("Cortney, Courtney, Curtis, Kurtis");
if (den==09) document.write("Dexter, Kyla, Kyle, Kyler");
if (den==10) document.write("Gabriel, Gabriela, Gabriele, Gabriella, Keeley");
if (den==11) document.write("Brad, Braden, Bradley, Brayden, Brooke, Brooks, Brooklyn");
if (den==12) document.write("Abraham, Ibrahim, Yvette");
if (den==13) document.write("Dane, Kendra, Nelson");
if (den==14) document.write("Amanda, Harmony, Mandy, Valentine");
if (den==15) document.write("Jordan, Jordon, Jordyn");
if (den==16) document.write("Elias, Elijah, Elliot, Gilbert, Gilberto, Ida, Sonny");
if (den==17) document.write("Clark, Clarke,  Bianca, Blanca, Blanche, Fiona");
if (den==18) document.write("Dale, Beatrice, Beatriz, Beau, Bebe");
if (den==19) document.write("Dodie, Dolly, Dora, Dorie, Doreen, Dorothea, Dorothy, Dorthy, Leland, Thea");
if (den==20) document.write("Orlando, Salma");
if (den==21) document.write("Byron, Eleanor, Lenora, Nell");
if (den==22) document.write("George, Georgia, Georgianne, Georgina, Gina, Jorge, Jordi");
if (den==23) document.write("Irvin, Irving, Nestor, Tatiana, Tatyanna");
if (den==24) document.write("Sergio, Belinda");
if (den==25) document.write("Federico, Fred, Freddie, Freddy, Frederic, Frederick, Fritz, Ola");
if (den==26) document.write("Jayna, Vicki, Vickie, Vicky, Victor, Victoria, Vikki");
if (den==27) document.write("Clyde, Farrah");
if (den==28) document.write("Amber, Osvaldo, Roderick, Rodrigo");
if (den==29) document.write("Everybody celebrates");
}
if (mesic==3) {
if (den==01) document.write("Graciela, Laverne, Rodger, Roger");
if (den==02) document.write("Cade, Caden, Imogene, Kaden");
if (den==03) document.write("Duane, Hattie");
if (den==04) document.write("Rhoda, Tyrone");
if (den==05) document.write("Lilia, Liliana, Lillian, Lillie, Lilly, Lily, Romeo");
if (den==06) document.write("Omar, Yvonne");
if (den==07) document.write("Earl, Gwendolyn");
if (den==08) document.write("Alaina, Alan, Alana, Alanna, Allan, Allen, Allyn, Lana");
if (den==09) document.write("Edgar, Edgardo, Jolene");
if (den==10) document.write("Barry, Hilda");
if (den==11) document.write("Angel, Angela, Angelia, Angelica, Angelina, Angeline, Angelique, Carroll, Angelo, Angie");
if (den==12) document.write("Aisha, Asha, Greg, Gregg, Gregorio, Gregory, Griffin, Keisha, Maisha, Myesha, Niesha");
if (den==13) document.write("Blake, Laila, Leila, Lela, Lelah");
if (den==14) document.write("Carson, Mildred, Virgil");
if (den==15) document.write("Rufus, Thelma");
if (den==16) document.write("Chance, Dallas, Lacey");
if (den==17) document.write("Pat, Patcy, Patricia, Patrice, Patrick, Patti, Pattie, Patty, Tricia, Trisha");
if (den==18) document.write("Blair, Ed, Eddie, Eddy, Eduardo, Edward, Edwardo, Gloria");
if (den==19) document.write("Jo, Joe, Jose, Josefina, Joseph, Josephine, Josie, Joey");
if (den==20) document.write("Lourdes, Spring, Zion");
if (den==21) document.write("Dalton, Daltin, Eileen, Ilene");
if (den==22) document.write("Shannon, Ty, Tyler, Tylor");
if (den==23) document.write("Adrian, Adriana, Adrianna, Adrien, Adrienne, Cedric, Cedrick");
if (den==24) document.write("Floyd, Lloyd, Ursula");
if (den==25) document.write("Armand, Herman, Marian, Marianne, Mario");
if (den==26) document.write("Carter, Olive");
if (den==27) document.write("Bradford, Gale, Galen, Payton, Peyton");
if (den==28) document.write("Ebony, Jermaine");
if (den==29) document.write("Lois, Willard");
if (den==30) document.write("Alma, Woodrow");
if (den==31) document.write("Bethany, Homer");
}
if (mesic==4) {
if (den==01) document.write("April, Mack");
if (den==02) document.write("Naomi, Noemi, Russell");
if (den==03) document.write("Dick, Mavis, Ricardo, Richard, Rick, Rickey, Ricki, Ricky, Rikki, Marlon");
if (den==04) document.write("Alethea, Alethia, Carlton, Drake, Magdalena, Magdalene, McKenzie, Mekenzie");
if (den==05) document.write("Abdul, Nadia, Nadine, Ryan, Rylan ");
if (den==06) document.write("Hugh, Hugo, Ira, Irene, Iris");
if (den==07) document.write("Bonita, Joel, Joelle, Kermit ");
if (den==08) document.write("Al, Albert, Alberta, Alberto, Elbert");
if (den==09) document.write("Ismael, Rachael, Rachel, Rachelle, Raquel");
if (den==10) document.write("Dion, Diona, Dione, Dionne, Beverly, Leroy");
if (den==11) document.write("Gillian, Jill, Jillian, Julia, Julian, Juliana, Julianna, Julianne, Julien, Juliet, Julio, Julius, Julie, Julliette");
if (den==12) document.write("Essie, Esther, Travis");
if (den==13) document.write("Charmaine, Misty, Mysta, Nolan");
if (den==14) document.write("Brady, Eula, Wallace");
if (den==15) document.write("Candace, Candice, Candy,  Emery, Emory, Isaiah");
if (den==16) document.write("Arlene, Arletta, Arline, Carlo, Carlos, Carol, Carole, Carolina, Caroline, Carrie, Carry, Charlene, Charles, Charlie, Chaz, Charlsie, Charlotte, Chuck, Ina, Karlene, Lottie, Sharla");
if (den==17) document.write("Callie, Rudolfo, Rudolph, Rudy");
if (den==18) document.write("Orville, Tamara, Tami, Tamia, Tammie, Tammy");
if (den==19) document.write("Marjorie, Otis, Otto");
if (den==20) document.write("Cinda, Cindy, Cynthia, Marcel, Marcelo, Tia, River");
if (den==21) document.write("Ignacio, Riley, Rylee");
if (den==22) document.write("Ada, Adah, Addie, Adela, Adelaide, Adele, Adelina, Adeline, Adina, Alda, Aleida, Alida, Alina, Aline, Brandon, Dede, Dell, Della");
if (den==23) document.write("Trinity, Tristan, Tristen, Tristin, Triston");
if (den==24) document.write("Ervin, Erwin, Dharma, Tara, Tarra, Taryn, Thora");
if (den==25) document.write("Marc, Mark, Marcus, Markus, Marco, Marcos, Marcy, Marcia, Marcela, Marcelino, Marcella, Marcel, Marcel, Marcelo, Marsha");
if (den==26) document.write("Shala, Shalanda, Tayler, Taylor, Yolanda");
if (den==27) document.write("Grant, Rory, Shara, Sharma, Sharmaine, Sharon, Shari");
if (den==28) document.write("Beulah, Chester");
if (den==29) document.write("Dante, Leticia, Zoe, Zoey");
if (den==30) document.write("Anastasia, Trent, Trenton");
}
if (mesic==5) {
if (den==01) document.write("May, Wyatt");
if (den==02) document.write("Miranda, Sheldon");
if (den==03) document.write("Brandi, Brandy, Lester");
if (den==04) document.write("Flora, Roy");
if (den==05) document.write("Sabrina, Tucker");
if (den==06) document.write("Carina, Carl, Carla, Carley, Carli, Carlie, Carly, Karl, Karla");
if (den==07) document.write("Mona, Monica, Monique,  Stewart");
if (den==08) document.write("Kiana, Levi, Lewis");
if (den==09) document.write("Roland, Rolando, Rollie, Selma");
if (den==10) document.write("Reagan, Regan, Viola, Violet");
if (den==11) document.write("Millie, Salvador, Salvatore");
if (den==12) document.write("Ginger, Ross, Virginia");
if (den==13) document.write("Fatima, Imelda, Linnea, Ramiro");
if (den==14) document.write("Flavia, Israel, Sybil");
if (den==15) document.write("Desiree, Meredith, Merrie, Zane");
if (den==16) document.write("Branden, Brant, Brenda, Brendan, Brenden, Brendon, Brenna, Brennan");
if (den==17) document.write("Brent, Eloise");
if (den==18) document.write("Aric, Eric, Erica, Erick, Ericka, Erik, Erika");
if (den==19) document.write("Gertrude, Saul, Trudy");
if (den==20) document.write("Bernard, Bernadette, Bernardo");
if (den==21) document.write("Freda, Micah");
if (den==22) document.write("Bret, Brett, Yesenia");
if (den==23) document.write("Clifford, Myrtle");
if (den==24) document.write("Jess, Jessica, Jesse, Jessie, Jessika");
if (den==25) document.write("Morgan, Rogelio, Waldo");
if (den==26) document.write("Bernice, Zachariah, Zachary, Zachery, Zackary");
if (den==27) document.write("Mayra, Mira, Myra, Preston");
if (den==28) document.write("Bill, Billie, Billy, Guillermo, Liam, Minnie, Twila, Velma, Vilma, Will, Willa, William, Willie, Willis, Wilma, Wilson, Wilhelmina");
if (den==29) document.write("Hilary, Hillary, Kennedy, Spencer");
if (den==30) document.write("Evan, Gianna, Giovanni, Jean, Jeanette, Jeanne, Jennell, Jeannette, Jeannine, Joan, Joann, Joanna, Joanne");
if (den==31) document.write("Doyle, Sharell, Sharyl, Shera, Sheree, Sherell, Sheri, Sherill, Sherrell, Sherri, Sherrie, Sherril, Sherrill, Sherry, Sherryl, Shery, Sheryl, Sheryl, Sheryll");
}
if (mesic==6) {
if (den==01) document.write("June, Justin, Justine, Dustin");
if (den==02) document.write("Brock, Myrna");
if (den==03) document.write("Ramon, Ramona, Ray, Raymond, Romona");
if (den==04) document.write("Elma, Kevin, Kevon");
if (den==05) document.write("Laura, Laurel, Lauren, Laurie, Lauryn, Lora, Lori, Lorean, Loree, Loren, Lorena, Lorene, Loretta, Lorette, Lorie, Lorina, Lorinda, Lorraine, Lorita, Lorrie, Lory, Loura");
if (den==06) document.write("Makena, Stuart");
if (den==07) document.write("Bert, Bob, Bobbi, Bobbie, Bobby, Robert, Roberta, Roberto, Robin, Robyny, Rupert");
if (den==08) document.write("Verna, Vernon");
if (den==09) document.write("Colin, Colleen, Collin");
if (den==10) document.write("Bryce, Bronwyn, Reyna");
if (den==11) document.write("Delores, Dolores, Deloris, Lola, Percy");
if (den==12) document.write("Malcolm, Evelyn");
if (den==13) document.write("Anton, Anthony, Antoine, Antoinette, Antonia, Antonie, Antonio, Latoya, Tona, Toni, Tonia, Tony, Tonya, Toya");
if (den==14) document.write("Mel, Melisa, Melissa, Melida, Melita, Melvin, Melvina, Missy");
if (den==15) document.write("Malvina, Vito, Wendell, Wendy");
if (den==16) document.write("Page, Todd");
if (den==17) document.write("Dixie, Junior");
if (den==18) document.write("Chantal, Colby, Lashawnda, Shawnda");
if (den==19) document.write("Garfield, Garth, Rhonda, Ronda, Myron");
if (den==20) document.write("Sherman, Valeria, Valerie, Valorie");
if (den==21) document.write("Shea, Summer, Terrance, Terrence");
if (den==22) document.write("Bailey, Baily, Paris");
if (den==23) document.write("Cher, Chere, Cheree, Cherelle, Cheri, Cherie, Cherilyn, Cherri, Cherrie, Cherry, Cherryl, Chery, Cheryl, Cheryle, Cheryll, Merlin");
if (den==24) document.write("Deshawn, Hans, Ian, Ivan, Iva, Jan, Johana, Johanna, John, Johna, Johnnie, Johnny, Joni, Johnson, Juan, Juana, Juanita, Junita");
if (den==25) document.write("Jana, Janae, Jane, Janelle, Janet, Janice, Janie, Sean, Shandi, Shan, Shandi, Shane, Shania, Shaun, Shawn, Shawna, Shawnee, Shayne, Sheena, Sina, Shon");
if (den==26) document.write("Kelvin, Serena, Serina");
if (den==27) document.write("Alec, Alejandra, Alejandro, Alex, Alexa,Alexander, Alexandra, Alexandria, Alexia, Alexis, Alexus, Alondra, Lex, Sandra, Sandy, Shandra, Sondra, Xander");
if (den==28) document.write("Clay, Clayton, Muriel");
if (den==29) document.write("Pablo, Paola, Paul, Pete, Paula, Paulette, Paulina, Pauline, Pedro, Peter, Pierce, Pierre, Petra");
if (den==30) document.write("Grady, Melanie, Melany, Melinda, Mindy");
}
if (mesic==7) {
if (den==01) document.write("Deana, Dean, Deeann, Deanna, Deanne, Dee, Deena, Diana, Diane, Dianna, Dianne, Dina, Dinah");
if (den==02) document.write("Bertha, Merle");
if (den==03) document.write("Madison, Maddison, Madyson, Toby");
if (den==04) document.write("America, Thomas, Tom, Tomas, Tommie, Tommy");
if (den==05) document.write("Aileen, Javier, Xavier");
if (den==06) document.write("Clifton, Gwen");
if (den==07) document.write("Livia, Oliver, Olivia, Ollie, Star, Starr");
if (den==08) document.write("Amado, Armand, Armando, Edna, Herman");
if (den==09) document.write("Elois, Eloisa, Eloise, Geoffrey, Jeff, Jeffery, Jeffrey, Lou, Louanne, Louie, Louis, Louise, Luana, Luanne, Luella, Luigi, Luis, Luisa");
if (den==10) document.write("Arthur, Arturo, Vanda, Walten, Wanda");
if (den==11) document.write("Joceline, Jocelyn, Joselyn, Koby");
if (den==12) document.write("Jay, Jason, Jayla, Jayson");
if (den==13) document.write("Guy, Margarita, Marge, Margie, Margaret, Maggie, Mamie, Marguerite, Marita, Meagan, Megan, Meghan, Peggy, Rita");
if (den==14) document.write("Don, Donald, Donna, Donnie, Donny, Donya, Ladonna");
if (den==15) document.write("Debbie, Debora, Deborah, Debra, Dillon, Dylan");
if (den==16) document.write("Jada, Jade, Jaden, Jadon, Jayden");
if (den==17) document.write("Glen, Glenda, Glenn, Glenna, Wayne");
if (den==18) document.write("Cameron, Camryn, Kameron, Kamryn");
if (den==19) document.write("Lea, Leah, Leigh, Winston");
if (den==20) document.write("Elijah, Ellis, Gilbert, Gilberto, Roxane, Roxanne");
if (den==21) document.write("Earnest, Ernest, Ernesto, Ernie");
if (den==22) document.write("Lowell, Madelein, Madeline, Madelyn");
if (den==23) document.write("Hayden, Helga, Olga");
if (den==24) document.write("Amaya, Amelia, Gisselle, Royce");
if (den==25) document.write("Coby, Jackson, Jacob, Jaime, Jakob, James, Jamey, Jamie, Jaymie, Jim, Jimmie, Jimmy, Kobe, Santiago, Ofelia");
if (den==26) document.write("Aine, Ana, Anais, Anika, Ann, Anna, Annabelle, Anne, Anita,  Annette, Annie, Annika, Annmarie, Bart, Hanna, Hannah, Hannelore, Nancy, Nanette, Nania, Nita");
if (den==27) document.write("Eli, Celia");
if (den==28) document.write("Calvin, Kim, Kimber, Kimberle, Kimberley, Kimberly");
if (den==29) document.write("Martha, Treva, Trevor");
if (den==30) document.write("Enrique, Harriet, Harriett, Harrison, Harry, Henrietta, Henry");
if (den==31) document.write("Delbert, Carmel, Carmela, Carmen");
}
if (mesic==8) {
if (den==01) document.write("August, Augustine, Augusto, Austen, Austin, Hope");
if (den==02) document.write("Leo, Leola, Leon, Leona, Leopoldo, Lionel");
if (den==03) document.write("Amira, Malic, Malika, Mallory, Soraya");
if (den==04) document.write("Dominic, Dominick, Domingo, Dominique");
if (den==05) document.write("Mackenzie, Makenzie, Oscar");
if (den==06) document.write("Hector, Lucy");
if (den==07) document.write("Donovan, Ethel");
if (den==08) document.write("Howard, Erma, Irma");
if (den==09) document.write("Gary, Garret, Garrett, Garry, Gerald, Geraldine, Geralyn, Gerard, Gerardo, Gerry, Jarret, Jerald");
if (den==10) document.write("Diego, Hailey, Haley, Hallie, Haylee, Haylie, Hayley, Lee");
if (den==11) document.write("Gage, Shanna, Sue, Susan, Susie, Suzanne");
if (den==12) document.write("Daren, Darin, Darla, Darlene, Darrell, Darren, Darrin, Darrlyn, Daryl");
if (den==13) document.write("Talia, Thalia, Van, Vance");
if (den==14) document.write("Cody, Heidi, Heidy, Kody");
if (den==15) document.write("Heaven, Nevaeh, Norma, Norman, Normandia");
if (den==16) document.write("Leonard, Leonardo, Lenny, Phyllis");
if (den==17) document.write("Clinton, Daisy");
if (den==18) document.write("Elaine, Elena, Eleni, Elina,  Ella, Helen, Helena, Helene, Lamar, Nellie");
if (den==19) document.write("Lydia, Ralph");
if (den==20) document.write("Arabella, Gavin");
if (den==21) document.write("Cornelius, Shelley, Shelly");
if (den==22) document.write("Macy, Wilbur");
if (den==23) document.write("Felipe, Kellee, Kelley, Kelli, Kellie, Kelly, Kiley, Kylee, Kylie, Phil, Philip, Phillip");
if (den==24) document.write("Owen, Desiree");
if (den==25) document.write("Pearl, Perla, Perry");
if (den==26) document.write("Sam, Samantha, Samira, Sammy, Samuel");
if (den==27) document.write("Silvia, Sylvia, Wade");
if (den==28) document.write("Gustavo, Niesha, Vivian, Viviana, Vivienne");
if (den==29) document.write("Jeremiah, Jeremy, Jeri, Jerri, Jerry");
if (den==30) document.write("Elmer, Destinee, Destiny");
if (den==31) document.write("Aden, Aidan, Aiden, Aydan, Ayden, Nora, Noreen, Sterling");
}
if (mesic==9) {
if (den==01) document.write("Ethan, Opal");
if (den==02) document.write("Linda, Lindsay Lindsey, Lyn, Lynda, Lynne, Lynette, Lynnette, Lynsey");
if (den==03) document.write("Horace, Dawn");
if (den==04) document.write("Grover, Rosa, Rosalind, Rosalinda, Rosalie, Rose, Roseann, Roseanne, Rosemarie, Rosemary, Rosetta, Rosie, Rosina");
if (den==05) document.write("Regina, Trey");
if (den==06) document.write("Ali, Alice, Alicia, Alisha, Alison, Alissa, Allison, Alycia, Allyson, Alyson, Alyssa, Terrell");
if (den==07) document.write("Dena, Deneen, Dina, Maurice, Mauricio");
if (den==08) document.write("Madeleine, Malia, Mara, Maren, Maria, Marie, Mariah, Mariana, Marilee, Mariella, Marla, Marilyn, Marisa, Marissa, Marion, Marlene, Mary, Maryann, Maryam, Mia, MaryLynn, Maureen, Miriam, Molly, Noah, Noe, Polly");
if (den==09) document.write("Conrad, Curt, Kurt, Eunice, Milo");
if (den==10) document.write("Damian, Damien, Damion, Damon, Tiffany");
if (den==11) document.write("Day of Rememberance");
if (den==12) document.write("Boyd, Gidget");
if (den==13) document.write("Fernando, Sierra");
if (den==14) document.write("Elton, Hazel");
if (den==15) document.write("Cara, Eldon, Kara");
if (den==16) document.write("Harley, Maia, Maya, Mya");
if (den==17) document.write("Celena, Celina, Celinda,Chandra, Luna, Salena, Salina, Selena, Selina, Wesley");
if (den==18) document.write("Dorian, Doris, Lucas, Lukas, Luke, Reilly");
if (den==19) document.write("Conner, Connie, Connor, Conor, Constance");
if (den==20) document.write("Ferdinand, Fernando, Michiko, Sofia, Sonia, Sonja, Sonya, Sophia, Sophie, Tanner, Vada, Veda");
if (den==21) document.write("Autumn, Matilda, Matt, Mathew, Matthew, Mattie, Tilda");
if (den==22) document.write("Morris, Whitney");
if (den==23) document.write("Ezra, Ninfa, Santos, Tiara");
if (den==24) document.write("Demetrius, McKenna");
if (den==25) document.write("Carey, Cary");
if (den==26) document.write("Eda, Edith, Ida, Moses");
if (den==27) document.write("Heath, Marina");
if (den==28) document.write("Milton, Selma, Shaina, Shayna");
if (den==29) document.write("Malaya, Mckayla, Micaela, Michael, Michaela, Micheal, Michelle, Miguel, Mika, Mike, Miles, Milo, Mitchell, Mickey, Myles");
if (den==30) document.write("Issac, Jerome, Lila");
}
if (mesic==10) {
if (den==01) document.write("Archibald, Archie, Arnaldo, Arnold, Aubrey");
if (den==02) document.write("Melody, Ruben, Ruby");
if (den==03) document.write("Ciara, Cierra, Jasper, Kairan, Keiron, Kiara, Kiera, Kieran, Kyran");
if (den==04) document.write("Buster, Fannie, Frances, Francesca, Francesia, Francine, Francis, Francisca, Francisco, Franco, Frank, Frankie");
if (den==05) document.write("Everett, Winifred, Winnie");
if (den==06) document.write("Blaine, Enid, Latasha, Natalia, Natalie, Natasha, Nathalie, Tasha ");
if (den==07) document.write("Birgit, Bridget, Bridgett, Brigette, Elicia, Elisha, Stone, Vaughn");
if (den==08) document.write("Emanuel, Emmanuel, Ezekiel, Immanuel, Manuel, Manuela, Manuella");
if (den==09) document.write("Christopher, Kristopher, Mercedes");
if (den==10) document.write("Hubert, Melia, Nina, Odessa");
if (den==11) document.write("Kira, Kirk");
if (den==12) document.write("Edwin, Heather, Lance, Max, Maxine, Maxvell");
if (den==13) document.write("Caleb, Kaleb, Lula, Skylar, Skyler");
if (den==14) document.write("Diamond, Lane, Layton");
if (den==15) document.write("Darnell, Tera, Teresa, Teri, Terri, Terry, Tess, Tessa, Theresa, Therese, Tracey, Traci, Tracie, Tracy");
if (den==16) document.write("Kayla, Kaylee, Monte, Monty");
if (den==17) document.write("Chasity, Chastity, Nia, Warren");
if (den==18) document.write("Cordelia, Delia, Marshall");
if (den==19) document.write("Chris, Christi, Christian, Christie, Christina, Christine, Christy, Cristina, Kirstie, Kirsten, Kris, Krista, Kristen, Kristi, Kristie, Kristin, Kristina, Kristine, Kristy, Tina");
if (den==20) document.write("Cleveland, Effie");
if (den==21) document.write("Craig, Cristal, Crystal, Kristal, Krystle");
if (den==22) document.write("Derek, Derrick, Faith");
if (den==23) document.write("Humberto, Kala, Sadie, Sallie, Sally, Sarah, Sarra, Sarina");
if (den==24) document.write("Lesa, Lesley, Leslie, Lesly, Wilfred, Wilfredo");
if (den==25) document.write("Camille, Randal, Randall, Randollph, Randy, Raul");
if (den==26) document.write("Leigh, Marvin");
if (den==27) document.write("Chloe, Ted, Theo, Theodore, Teddy");
if (den==28) document.write("Reyna, Reynaldo, Reynold, Stacey, Staci, Stacie, Stacy");
if (den==29) document.write("Clair, Clara, Clarence, Clarice, Clarissa");
if (den==30) document.write("Herbert, Heriberto, Simon, Simona, Simone, Simonne");
if (den==31) document.write("Audra, Audrey, Audrie, Audry, Deirdre, Landon");
}
if (mesic==11) {
if (den==01) document.write("Denise, Dennis, Dwight, Sidney, Sydney");
if (den==02) document.write("Bella, Mason, Shelb");
if (den==03) document.write("Rafael, Mabel, Mable, Mae");
if (den==04) document.write("Estella, Estelle, Hugh");
if (den==05) document.write("Chad, Chase, Chelsea, Chelsey, Cheryl, Edwin");
if (den==06) document.write("Breana, Breanna, Bree, Brian, Briana, Brianna, Brianne, Bryan, Bryana, Bryanna, Bryant");
if (den==07) document.write("Rena, Rene, Renea, Renee");
if (den==08) document.write("Logan, Scarlett, Stella, Sunni, Sunny");
if (den==09) document.write("Rocco, Rochelle, Rocky");
if (den==10) document.write("Nettie, Raven, Reuben, Tabitha");
if (den==11) document.write("Etta, Quentin, Quincy, Quinton");
if (den==12) document.write("Jewel, Jewell, Lyle");
if (den==13) document.write("Mallory, Stan, Stanley");
if (den==14) document.write("Lara, Larissa, Larry, Laurence, Lawrence, Lorenzo");
if (den==15) document.write("Delaney, Sherley, Sherly, Shirely, Shirey, Shirl, Shirlee, Shirley, Shirly");
if (den==16) document.write("Adolfo, Grace, Gracie, Royal");
if (den==17) document.write("Claude, Claudia, Claudette, Clint, Gladys");
if (den==18) document.write("Eugenia, Gene");
if (den==19) document.write("Alton, Bessie, Beth, Betty, Elsa, Else, Elisa, Elise, Elisabeth, Elissa, Eliza, Elizabeth, Ellie, Elsie, Elyse, Isabell, Isabella, Isabelle, Lisa, Lisette, Liz, Lizabeth");
if (den==20) document.write("Edmond, Edmund, Felicia, Felicity, Felix");
if (den==21) document.write("Elvira, Reyes, Rex, Rhiannon, Soledad");
if (den==22) document.write("Cecelia, Cecil, Cecile, Cecilia, Elia, Eliana, Leanna, Murray, Shayla, Sheila, Shelia");
if (den==23) document.write("Bud, Buddy, Cheyenne, Dakota, Savanna, Savannah");
if (den==24) document.write("Aurora, Kigan");
if (den==25) document.write("Caitlin, Caitlyn, Catalina, Cate, Catherine, Cathy, Caryn, Jamal, Kaitlin, Kaitlyn, Kari, Katharine, Katherine, Kathleen, Kathrin, Kathryn, Katie, Karen, Katya, Trina");
if (den==26) document.write("Asia, Ermelinda, Fern, Herlinda, Hermelinda, Keith, Keitha");
if (den==27) document.write("Dwight, Erin, Eryn");
if (den==28) document.write("Penelope, Penni, Penney, Pennie, Penny, Scott");
if (den==29) document.write("Kai, Kay, Troy");
if (den==30) document.write("Andre, Andrea, Andreas, Andres, Andrew, Andy, Deandre, Drew");
}
if (mesic==12) {
if (den==01) document.write("Aaliah, Aaron, Aliyah, Aron, Rhea");
if (den==02) document.write("Pam, Pamela, Sebastian");
if (den==03) document.write("Duncan, Graham, Luther, Ora");
if (den==04) document.write("Barbara, Barbie, Barbra, Rodney");
if (den==05) document.write("Abel, Beckie, Becky, Reba, Rebeca, Rebecca, Rebekah");
if (den==06) document.write("Nicholas, Nichole, Nico, Nicolas, Nicolette, Nicole, Nick, Nickolas, Nikki");
if (den==07) document.write("Parker, Melba");
if (den==08) document.write("Charis, Charise, Charissa, Charisse, Concetta, Desmond, Elva");
if (den==09) document.write("Luz, Lyman, Pandora, Roman");
if (den==10) document.write("Emma, Emmet, Emmett");
if (den==11) document.write("Arianna, Ariane, Arianne, Ken, Kenneth, Kenny");
if (den==12) document.write("Guadalupe, Joaquin, Lupe");
if (den==13) document.write("Efrain, Lucia, Lucile, Lucille, Lucinda, Lucy");
if (den==14) document.write("Gordon, Ingrid");
if (den==15) document.write("Aiyana, Ayana, Ayanna, Darwin, Walker");
if (den==16) document.write("Aida, Dewitt, Garland");
if (den==17) document.write("Britt, Britney, Brittany, Brittney, Bruce");
if (den==18) document.write("Fletcher, Genna, Harlan, Jenifer, Jenna, Jennie, Jennifer, Jenny");
if (den==19) document.write("Daria, Dario, Darius, JoDee, Jodi, Jodie, Jody, Jude, Judi, Judie, Judith, Libby");
if (den==20) document.write("Dagmar, Dwayne, Ruth");
if (den==21) document.write("Ezekiel, Ivy");
if (den==22) document.write("Elia, Eliana, Josh, Joshua, Josue, Lee, Leann, Leanna, Leanne");
if (den==23) document.write("Addison, Jared, Jarred, Jarrod, Jerred, Jerrod, Tory");
if (den==24) document.write("Adam, Adan, Eden, Eva, Eve, Herta, Hertha");
if (den==25) document.write("Jesus");
if (den==26) document.write("Esteban, Estefania, Noel, Stefan, Stefanie, Stephan, Stephanie, Stephany, Stephen, Steve, Steven");
if (den==27) document.write("Golda, Goldie, Gemma, Lamont");
if (den==28) document.write("Burton, Cassie");
if (den==29) document.write("Dave, David, Davis, Dawson, Dewey, Kali");
if (den==30) document.write("Abbie, Abby, Abigail, Gail, Gayla, Gayle, Tyson");
if (den==31) document.write("Silvester, Geneva, Genevieve");
	document.write("");
	}